<div style="background-color:white">
<div class="container shadow" style="min-width:950px;width:auto;margin:0px 100px;font-size:13px">
<p style="font-size:14px"><b>Online shopping India</b></p>
<p>Imagine you are in dire need of new sports shoes and have to get them before the weekend. Are you willing to take a day off from work just to go hunting for a pair in the crowded malls, foraging through endless shops for the right designs and color options? Will you wait in never-ending queues in front of the billing counter? Oh, and are you willing to pay the MRP for something that you could get for less? Are you willing to face so many hardships just for a pair of sports shoes? Or do you want to sit in your air-conditioned office, work diligently on your projects, impress your seniors, and during the coffee break, browse through the massive selection of sports footwear on LocalKart. See how easy shopping on LocalKart is! You do not have to embark on Tolkien-like quests for your shopping needs. Just wish for something and we will deliver.</p>
<p>
<b>LocalKart Matlab Bilkul Pakka</b><br>
When you shop on LocalKart you can rest assured about the quality of the products you're buying. Together with our trusted brand partners, we promise to deliver only brand-new, original products with the bill, and at prices that will make you squeal with joy! You should also know that we use secure payment gateways and keep your transaction details confidential. If you're still hesitant about choosing online payment methods that involve net-banking, or credit or debit cards, you could opt for the Cash-on-Delivery method, and incur no extra charges. When your order reaches you, you can even pay the amount with your card.Imagine that you liked a pair of jeans on LocalKart; the price, color, everything was to your liking, so you bought it instantly. But when your order reached you, you found the jeans to be a tad bit too tight or loose for your liking, or you are unhappy with the product for some reason. In such cases, you can easily return the product and get your money back, or you can return it and ask LocalKart to replace it with another size, for the same price. The Bilkul Pakka guarantee ensures that you have an amazing shopping experience with us, even when it involves exchanging a product, or returning it and getting a full refund for it.</p>
<p>
<b>The new age of gifting - LocalKart E-Gift Vouchers</b><br>
Your best friend is getting married and you don't know what you should get him and his wife for a wedding present. You're not sure if their new house needs a microwave oven or a coffee table. We understand that people often find themselves in such situations, and that's why we have LocalKart E-Gift Vouchers. Instead of getting your friends a gift of your choice and finding out later that they already had it, or just didn't like it as much as you thought, you could just give them these vouchers that they can redeem on LocalKart. That way, they will be able to buy exactly what they need.</p>
<p><b>With EMI every luxury is affordable.</b><br>
Your old mobile has given up and you have to buy a new one. But this time you want to go for a feature-rich, sleek smartphone. As fate would have it, it is the middle of the month, you are almost broke and pay day seems too far away. What will you do? Beg, borrow, steal? There's no need to do any of that. You could just buy your sexy new phone on EMI at our online shopping site.</p> 
<p><b>Want to understand a product better? Look through our buying guides.</b><br>
So you want to buy an air conditioner for your home, but you don't understand head or tail about these products. When you look through the massive list of specifications, the words look like Greek and Latin to you. How do you know which AC will be right for your bedroom? Our buying guides will help you in such situations. We have a number of buying guides for various categories of products to make your LocalKart shopping experience the best ever.</p>
<p><b>Shop on the app</b><br>
Oh, and you can shop with us on your smartphone, too. Just download our app and shop on it anywhere, anytime.<br>
So, tell us, what do you wish for today?</p>
</div></div></body>
</html>